---
name: Check 🛠

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  r-cmd-on-windows:
    name: R CMD Check on Windows🧬
    uses: arkadiuszbeer/r.pkg.template/.github/workflows/build-check-install-on-windows.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      additional-env-vars: |
        _R_CHECK_CRAN_INCOMING_REMOTE_=false
      additional-r-cmd-check-params: --as-cran
